"""Aria — choking detection audio model.

Custom-trained 1D-mel-CNN. Trained from scratch on a mix of public audio
clips (ESC-50 / FSD50K classes) and synthetic respiratory-distress signals
generated by aria.synth. Exported to ONNX for in-browser inference.
"""

from aria.model import AriaModel
from aria.audio import compute_mel_spectrogram, MEL_BINS, SAMPLE_RATE, WINDOW_SECONDS

__all__ = ["AriaModel", "compute_mel_spectrogram", "MEL_BINS", "SAMPLE_RATE", "WINDOW_SECONDS"]
__version__ = "0.1.0"
